### ISSUE TITLE
Can't build/run current master

### ISSUE THREAD

**Issue by hartzell** [zz85/space-radar#23]
I'm interested in using space-radar to view data from a remote server.  That feature does not appear to be in any of the release versions, so I've tried to build from master.  I know next to nothing about electron or the node ecosystem....

I'm on a Mac running OS X 10.11.2

I cloned the repo, ran `npm install electron-packager --save-dev`, then `npm run build`.  The resulting .app does this when I run it:

![screen shot 2016-10-27 at 8 56 56 am](https://cloud.githubusercontent.com/assets/312978/19774879/686669ca-9c23-11e6-95f6-5616ba3b29a1.jpg)

`npm install electron` and then `npm run app` does this:

```
hartzelg-UXG8WL:space-radar hartzelg$ npm run app

> space-radar@4.5.0 app /Users/hartzelg/tmp/space-radar
> electron .

App threw an error during load
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/hartzelg/tmp/space-radar/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/hartzelg/tmp/space-radar/main.js:4:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
^C
```

and after `npm install standard`, running `npm run test` complains vociferously.

Can you share instructions on how to make this work?

Or, can you release (preview release?) a version that includes the "read data from file" functionality?

Thanks!

**Comment by zz85** [comment]
v5 builds are out. https://github.com/zz85/space-radar/releases/tag/v5.1.0

For development now, you should run

```sh
npm install
npm run install
npm run debug
```
